#############################################################################
# Makefile for building: XMLGeneratorApp.app/Contents/MacOS/XMLGeneratorApp
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  ../XMLGeneratorApp/XMLGeneratorApp.pro
# Template: app
# Command: /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -o Makefile ../XMLGeneratorApp/XMLGeneratorApp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../XMLGeneratorApp -I. -I/usr/local/include/opencv -I/usr/local/include -I../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers -I../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers -I../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib
QMAKE         = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = XMLGeneratorApp1.0.0
DISTDIR = /Users/arqam/Downloads/build-XMLGeneratorApp-Desktop_Qt_5_10_0_clang_64bit-Debug/.tmp/XMLGeneratorApp1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../XMLGeneratorApp/main.cpp \
		../XMLGeneratorApp/mainwindow.cpp \
		../XMLGeneratorApp/imagelist.cpp \
		../XMLGeneratorApp/dlibxml.cpp \
		../XMLGeneratorApp/betafacepoints.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		imagelist.o \
		dlibxml.o \
		betafacepoints.o \
		moc_mainwindow.o
DIST          = ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		../XMLGeneratorApp/.qmake.stash \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf \
		../XMLGeneratorApp/XMLGeneratorApp.pro ../XMLGeneratorApp/mainwindow.h \
		../XMLGeneratorApp/imagelist.h \
		../XMLGeneratorApp/dlibxml.h \
		../XMLGeneratorApp/betafacepoints.h ../XMLGeneratorApp/main.cpp \
		../XMLGeneratorApp/mainwindow.cpp \
		../XMLGeneratorApp/imagelist.cpp \
		../XMLGeneratorApp/dlibxml.cpp \
		../XMLGeneratorApp/betafacepoints.cpp
QMAKE_TARGET  = XMLGeneratorApp
DESTDIR       = 
TARGET        = XMLGeneratorApp.app/Contents/MacOS/XMLGeneratorApp

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d XMLGeneratorApp.app/Contents/MacOS/ || mkdir -p XMLGeneratorApp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../XMLGeneratorApp/XMLGeneratorApp.pro ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf \
		../XMLGeneratorApp/XMLGeneratorApp.pro \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/QtXml.prl \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ../XMLGeneratorApp/XMLGeneratorApp.pro
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/link_pkgconfig.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf:
../XMLGeneratorApp/XMLGeneratorApp.pro:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/QtXml.prl:
../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../XMLGeneratorApp/XMLGeneratorApp.pro

qmake_all: FORCE

XMLGeneratorApp.app/Contents/PkgInfo: 
	@test -d XMLGeneratorApp.app/Contents || mkdir -p XMLGeneratorApp.app/Contents
	@$(DEL_FILE) XMLGeneratorApp.app/Contents/PkgInfo
	@echo "APPL????" > XMLGeneratorApp.app/Contents/PkgInfo
XMLGeneratorApp.app/Contents/Resources/empty.lproj: 
	@test -d XMLGeneratorApp.app/Contents/Resources || mkdir -p XMLGeneratorApp.app/Contents/Resources
	@touch XMLGeneratorApp.app/Contents/Resources/empty.lproj
	
XMLGeneratorApp.app/Contents/Info.plist: 
	@test -d XMLGeneratorApp.app/Contents || mkdir -p XMLGeneratorApp.app/Contents
	@$(DEL_FILE) XMLGeneratorApp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Mobigraph.XMLGeneratorApp,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,XMLGeneratorApp,g" -e "s,@LIBRARY@,XMLGeneratorApp,g" -e "s,@TYPEINFO@,????,g" ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/Info.plist.app >XMLGeneratorApp.app/Contents/Info.plist

all: Makefile \
		XMLGeneratorApp.app/Contents/PkgInfo \
		XMLGeneratorApp.app/Contents/Resources/empty.lproj \
		XMLGeneratorApp.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../XMLGeneratorApp/mainwindow.h ../XMLGeneratorApp/imagelist.h ../XMLGeneratorApp/dlibxml.h ../XMLGeneratorApp/betafacepoints.h $(DISTDIR)/
	$(COPY_FILE) --parents ../XMLGeneratorApp/main.cpp ../XMLGeneratorApp/mainwindow.cpp ../XMLGeneratorApp/imagelist.cpp ../XMLGeneratorApp/dlibxml.cpp ../XMLGeneratorApp/betafacepoints.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../XMLGeneratorApp/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r XMLGeneratorApp.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPen \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		../XMLGeneratorApp/mainwindow.h \
		moc_predefs.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/moc
	/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang -I/Users/arqam/Downloads/XMLGeneratorApp -I/usr/local/include/opencv -I/usr/local/include -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib ../XMLGeneratorApp/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../XMLGeneratorApp/mainwindow.ui \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/uic
	/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/uic ../XMLGeneratorApp/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../XMLGeneratorApp/main.cpp ../XMLGeneratorApp/mainwindow.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPen \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../XMLGeneratorApp/main.cpp

mainwindow.o: ../XMLGeneratorApp/mainwindow.cpp ../XMLGeneratorApp/mainwindow.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPen \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		ui_mainwindow.h \
		../XMLGeneratorApp/imagelist.h \
		../XMLGeneratorApp/betafacepoints.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../XMLGeneratorApp/dlibxml.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers/QCloseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../XMLGeneratorApp/mainwindow.cpp

imagelist.o: ../XMLGeneratorApp/imagelist.cpp ../XMLGeneratorApp/imagelist.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QIODevice \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qiodevice.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagelist.o ../XMLGeneratorApp/imagelist.cpp

dlibxml.o: ../XMLGeneratorApp/dlibxml.cpp ../XMLGeneratorApp/dlibxml.h \
		../XMLGeneratorApp/imagelist.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		../XMLGeneratorApp/betafacepoints.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/qdom.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomElement \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomText \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlibxml.o ../XMLGeneratorApp/dlibxml.cpp

betafacepoints.o: ../XMLGeneratorApp/betafacepoints.cpp ../XMLGeneratorApp/betafacepoints.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../XMLGeneratorApp/imagelist.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/qdom.h \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomElement \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtXml.framework/Headers/QDomText \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o betafacepoints.o ../XMLGeneratorApp/betafacepoints.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

